import { roboto } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} h-screen w-screen bg-slate-50 text-ttt_dark_blue_500`}
      >
        {children}
      </body>
    </html>
  );
}
